/// <autosync enabled="true" />
/// <reference path="../lib/jquery/jquery-3.7.1.js" />
// /// <reference path="../lib/jasmine-2.3.4/boot.js" />
// /// <reference path="../lib/jasmine-2.3.4/console.js" />
// /// <reference path="../lib/jasmine-2.3.4/jasmine.js" />
// /// <reference path="../lib/jasmine-2.3.4/jasmine-html.js" />
/// <reference path="linqJs/linqify.js" />
/// <reference path="linqJs/linq-core.js" />
/// <reference path="linqJs/linqify-jquery.js" />
/// <reference path="linqJs/typeDefs.js" />
/// <reference path="linqJs/Tests.js" />
/// <reference path="specs/aggregate.test.js" />
/// <reference path="specs/aggregateWithSeed.test.js" />
/// <reference path="specs/aggregateWithSeedAndResultSelector.test.js" />
/// <reference path="specs/all.test.js" />
/// <reference path="specs/any.test.js" />
/// <reference path="specs/average.test.js" />
/// <reference path="specs/averageWithTransform.js" />
/// <reference path="specs/concat.test.js" />
/// <reference path="specs/contains.js" />
/// <reference path="specs/count.test.js" />
/// <reference path="specs/defaultIfEmpty.js" />
/// <reference path="specs/distinct.test.js" />
/// <reference path="specs/elementAt.js" />
/// <reference path="specs/except.js" />
/// <reference path="specs/first.js" />
/// <reference path="specs/firstOrDefault.test.js" />
/// <reference path="specs/forEach.test.js" />
// /// <reference path="specs/getEnumerator.js" />
/// <reference path="specs/groupBy.test.js" />
/// <reference path="specs/helloWorld.test.js" />
/// <reference path="specs/intersect.test.js" />
/// <reference path="specs/last.test.js" />
/// <reference path="specs/max.js" />
/// <reference path="specs/min.js" />
/// <reference path="specs/orderBy.js" />
/// <reference path="specs/orderByDescending.js" />
/// <reference path="specs/reverse.js" />
/// <reference path="specs/select.js" />
/// <reference path="specs/selectMany.js" />
/// <reference path="specs/setValue.js" />
/// <reference path="specs/single.js" />
/// <reference path="specs/singleOrDefault.js" />
/// <reference path="specs/skip.js" />
/// <reference path="specs/skipWhile.js" />
/// <reference path="specs/sum.js" />
/// <reference path="specs/take.js" />
/// <reference path="specs/takeWhile.js" />
/// <reference path="specs/union.js" />
/// <reference path="specs/where.js" />
/// <reference path="specs/zip.js" />
